### ISSUE TITLE
Feature Request: Highlight results on page

### ISSUE THREAD

**Issue by disconsented** [Mohd-PH/RegexSearch#1]
Would be handy to be able to highlight results in page as they appear.

**Comment by Mohd-PH** [comment]
Thank you for requesting this feature, however the plugin meant to extract the information from HTML document and display it in the results area.

**Comment by AllanLRH** [comment]
I also think that highlighting the text would be a killer feature!

**Comment by Mohd-PH** [comment]
Sure then, I need to refactor the code and try to implement this feature, I am quite busy the next two weeks so I don’t think its going to be soon, sorry

**Comment by AllanLRH** [comment]
No worries, I'm just glad that you're up for looking into it.
This is the best regex-plugin I've found for Firefox so far, so it's nice that it's going to even better :)

**Comment by Mohd-PH** [comment]
Oh I am glad you like it 😄

**Comment by Mohd-PH** [comment]
Hi, sorry for taking too long
Here is the add-on please try it and tell me what you think and what I should improve
 [Link](https://github.com/Mohd-PH/RegexSearch/releases/tag/1.0.3b)
@disconsented @AllanLRH

**Comment by AllanLRH** [comment]
I like the highlight option, it's something like that which I was looking for :)

**Comment by disconsented** [comment]
Works quite well but it highlights the XML in the page, for example searching for '/br/' will result in 
![image](https://user-images.githubusercontent.com/1381469/33234908-28ba855c-d293-11e7-9714-c769f64652a4.png)

**Comment by Mohd-PH** [comment]
Thanks for sharing @disconsented , the problem is when highlighting I shouldn't ignore HTML tags , but I will try to find a work around for it.

**Comment by Mohd-PH** [comment]
Couldn't find a solution for this issue @disconsented , but you can use this regex `/[^<]br/`
Please keep the issue open I might find a solution in the future

**Comment by Mohd-PH** [comment]
Hi @disconsented , so I used a new way for highlighting, check out the [new release 1.0.6](https://github.com/Mohd-PH/RegexSearch/releases/tag/1.0.6)
