### ISSUE TITLE
Option for highlight colour

### ISSUE THREAD

**Issue by freefalltom** [Mohd-PH/RegexSearch#18]
Hi - is there any possibility of having an option for the colour of the highlight?
I use your RegexSearch add-on primarily on a screen where we already use the same colour to highlight particular items... being able to change the highlight colour in Regex would be exceedingly useful for me to pick out other things, as I'm unable to change it on our internal page.
(If I get time, I'll have a look and see if I can suggest code, but it will be a big learning curve as I've never touched FF add-ons before)
Thanks, Tom

**Comment by theDragonFire** [comment]
Hey, I have some code ready for this. I'm still working out a couple issues with pull requests, branches, etc. that's stopping me from submitting a PR. If @Mohd-PH accepts my other PR (#19), then I can submit my PR for this issue. Meanwhile, I'm going to try and work it out so that I can submit them in parallel. Hope it gets to you as soon as possible!

**Comment by freefalltom** [comment]
Hi - thanks for picking up on this.  I hope your changes are accepted soon, although there's no rush from my point of view :-)

**Comment by Mohd-PH** [comment]
Thank you for your suggestion, @theDragonFire has implemented this feature, the new version has been uploaded to Firefox's add-ons website and in the releases page here in GitHub.

**Comment by freefalltom** [comment]
That's great - thank you both for the exceptionally quick turn around :-)
One very minor bug is that if you come all the way out of the "Regex Search" options it doesn't re-select the pre-defined colour radios (green, pink, etc) or user-defined radio/textbox when you go back in.  (It does re-select if you close the colour popup and then go straight back into the colour popup, but not if you come all the way out.)
Also, if I'm being **really** picky, the radio should also react when you click on the title (using `<label` for="...">`).
But neither are show-stoppers, so thanks again to you both.
Cheers, Tom
