### ISSUE TITLE
Works on some pages, but not others

### ISSUE THREAD

**Issue by chriswjohnson** [Mohd-PH/RegexSearch#22]
Thank you for this much needed add-on. Unfortunately, it works on same web pages, but not others. For example, a case-insensitive, global search for "regex" works on <https://github.com/Mohd-PH/RegexSearch/>, but does nothing on <https://addons.mozilla.org/en-US/firefox/addon/regexsearch/>. Enabling or disabling the "Ignore HTML" option does not affect this issue.

Those tests were performed using RegexSearch 1.0.17 and Firefox 68.0.1 (64-bit) on macOS 10.13.6.

**Comment by Mohd-PH** [comment]
Thank you for reaching out
Actually addons are blocked on https://addons.mozilla.org
Please refer to the 3rd yellow box in this page https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Modify_a_web_page

> Note that although this video shows the content script working in addons.mozilla.org, content scripts are currently blocked for this site.

**Comment by theDragonFire** [comment]
For the reference of others who look at this issue, a full list of URLs where addons are blocked can be found [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts) in the first warning box. For those who don't care to read the link, the list at the time of writing is:
* accounts-static.cdn.mozilla.net
* accounts.firefox.com
* addons.cdn.mozilla.net
* addons.mozilla.org
* api.accounts.firefox.com
* content.cdn.mozilla.net
* content.cdn.mozilla.net
* discovery.addons.mozilla.org
* input.mozilla.org
* install.mozilla.org
* oauth.accounts.firefox.com
* profile.accounts.firefox.com
* support.mozilla.org
* sync.services.mozilla.com
* testpilot.firefox.com

**Comment by theDragonFire** [comment]
@Mohd-PH You may want to make note of this in the add-on description (at least noting addons.mozilla.org)

**Comment by Mohd-PH** [comment]
Done it
Thanks for the suggestion 🔥🐉

**Comment by chriswjohnson** [comment]
OK. Wasn't expecting that. I thought by choosing the add-on's own page on the mozilla site, I'd chosen the simplest and most obvious example available, which I'd hoped would be helpful. (Sigh.)

Here's a less simple and common example: <https://docs.oracle.com/javase/8/docs/api/index.html>. I suspect frames are the issue, because opening, for instance, the contents of <https://docs.oracle.com/javase/8/docs/api/overview-summary.html> in a window/tab by itself allows Regex Search to work as expected.

**Comment by theDragonFire** [comment]
Yeah, I think you're right. In page_search.js at lines 7 & 32, it uses `document.body.innerText`, `document.body.innerHTML`, and `document.body`. However, when I printed those out in the console, `innerText` resulted in `""` and `innerHTML` results in
```
"
<frameset rows=\"30%,70%\" title=\"Left frames\" onload=\"top.loadFrames()\">
<frame src=\"overview-frame.html\" name=\"packageListFrame\" title=\"All Packages\">
<frame src=\"allclasses-frame.html\" name=\"packageFrame\" title=\"All classes and interfaces (except non-static nested types)\">
</frameset>
<frame src=\"overview-summary.html\" name=\"classFrame\" title=\"Package, class and interface descriptions\" scrolling=\"yes\">
<noframes>
<noscript>
<div>JavaScript is disabled on your browser.</div>
</noscript>
<h2>Frame Alert</h2>
<p>This document is designed to be viewed using the frames feature. If you see this message, you are using a non-frame-capable web client. Link to <a href=\"overview-summary.html\">Non-frame version</a>.</p>
</noframes>
"
```
Unfortunately, the contents of the page don't seem to be available to the code, at least not the way it is being done currently. And as far as I know, there is no other way to do it that would work with the extension. Oracle would have to change the structure of their documentation.

(And they probably should because according to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/frame)
> Using the \<frame\> element is not encouraged because of certain disadvantages such as 
> performance problems and lack of accessibility for users with screen readers.

)

**Comment by chriswjohnson** [comment]
Agreed. Frames are bad. (And Oracle does seem to have abandoned frames in the documentation for more recent Java versions. Unfortunately, they did so without supplying comparable replacement functionality.)

Anyway, thanks for investigating.
