### ISSUE TITLE
Any thoughts on Chrome support?

### ISSUE THREAD

**Issue by geekscrapy** [Mohd-PH/RegexSearch#23]
Love this extension, wondered if you had any thoughts on support for Chrome?

**Comment by Mohd-PH** [comment]
Thank you
As for chrome when I started making this extension, I was looking for similar extensions on chrome or Firefox, I've found multiple extensions for chrome but none for Firefox.
So I decided to make it only for Firefox.

Examples for chrome extensions:
https://chrome.google.com/webstore/detail/chrome-regex-search/bpelaihoicobbkgmhcbikncnpacdbknn
https://chrome.google.com/webstore/detail/regex-matcher/jkokpkcggnifdedpaicbjcapmhiecjjk

I might add chrome support to my extension, but not in the near future 😅
