### ISSUE TITLE
is negative lookahead supported?

### ISSUE THREAD

**Issue by 8712staefa** [Mohd-PH/RegexSearch#24]
Negative lookahead (?!.....) does not seem to work in Mac Firefox 71. I get slow down warnings even after 40s (default 10s).

**Comment by SethFalco** [comment]
I've just tested this and found that negative lookaheads appear to be working fine.
I'm using Ubuntu 18.04, Firefox 85.0.1 (64-bit).

I tested this page with `Negative(?![ (])` which failed to find any results. Whereas `Negative(?!F)` successfully matched the word in the issue title and first comment.

It'd probably have helped to include an example webpage and regex so the issue could be reproduced.
