### ISSUE TITLE
Will a Windows XPI work on Linux?

### ISSUE THREAD

**Issue by ak2766** [Mohd-PH/RegexSearch#3]
I'm here as you posted the link to this github page in response to my review on Firefox Addons.  However, on visiting the .../releases page, I see links for Windows XPI files - will this work on Linux?

**Comment by Mohd-PH** [comment]
@ak2766   Yeah it works just fine. tried it on Firefox on Linux mint

**Comment by ak2766** [comment]
Awesome, Thanks. Will deploy it soon...

**Comment by Mohd-PH** [comment]
You are welcome!

**Comment by ak2766** [comment]
OK - installed it and I see the Highlight option - awesome!

I noticed the regex engine doesn't honor the non-greedy (aka lazy) quantifier `*?` - any plans to add that in the near future (see below for what I use it for)?

* Use Case:

I was trying to get the definition of FFI on [this site](http://luajit.org/ext_ffi.html) (_**hint**:, acronym wasn't defined on the page_) with this regex `f[^ ]* f[^ ]* i[^ ]* `, it found this instead:
```
floor

local function image_ramp_green(n)
 ```
I then attempted to modify my regex with the lazy quantifier `f[^ ]*? f[^ ]*? i[^ ]*? ` to no avail.

For completeness sake, I was able to find the definition of FFI (Foreign Function Interface) on [this page](https://www.freelists.org/post/luajit/What-does-FFI-stand-for,1) where I found an oddity - the addon modifies the page repeatably:

* Visit [this page](https://www.freelists.org/post/luajit/What-does-FFI-stand-for,1)
* Click the addon icon
* enter this regex - `<f[^ ]* f[^ ]* i[^ ]* >` (**copy regex within `<` `>` delimeters**)
* select `Case-insensitive`
* click `Search`
* repeatedly click `Highlight`

**Comment by Mohd-PH** [comment]
I am sorry @ak2766 I couldn't reproduce your case, however the plugin uses Javascript to search in the document.body, and Javascript supports non-greedy quantifier. you can reference [this article ](https://javascript.info/regexp-greedy-and-lazy)
I tried these regular expressions on [example.com](example.com)
non-greedy:
```
domain .*?e
```
greedy:
```
domain .*e
```
and they work just fine

**Comment by ak2766** [comment]
Interesting that it works for you.  I'll try with a clean browser profile and see if it is perhaps caused by some conflicting addon in mine.
