### ISSUE TITLE
Characters beyond 7-bit ASCII don't match correctly as word/boundary/...

### ISSUE THREAD

**Issue by jmbreuer** [Mohd-PH/RegexSearch#32]
From a concrete example - I'm looking to match "words starting with a specific letter", e.g. with `\bn\w+` (case-insensitive, global), in this example matching words starting with the letter `N`.

Unfortunately, extended ASCII/Unicode/... characters are not considered as word characters, but rather as boundaries - in this example, the portion `ngegleiter` of the German word `Hängegleiter` is matched as a word starting with n, i.e. the `ä` is wrongly considered a non-word character.

Ideally, it should match characters according to their defined [Unicode character category](https://www.compart.com/en/unicode/category).

**Comment by Mohd-PH** [comment]
Thank you @jmbreuer, I guess it's an issue in the JavaScript regular expression matching

given that, a workaround in writing the regular expression is possible

please see: https://stackoverflow.com/questions/10590098/javascript-regexp-word-boundaries-unicode-characters

**Comment by jmbreuer** [comment]
I see, thank you, @Mohd-PH! That workaround does solve my use case.
