### ISSUE TITLE
Add keyboard shortcut

### ISSUE THREAD

**Issue by haarp** [Mohd-PH/RegexSearch#4]
Hey,

nifty addon, thanks for making it!

It would be cool if there was a keyboard shortcut to bring up the search and focus the regex field, similar to what Ctrl+F does for the integrated search. Maybe Ctrl+Shift+F?

Thanks!

**Comment by Mohd-PH** [comment]
Hmm interesting, thanks for suggesting, I will look into it

**Comment by Mohd-PH** [comment]
Done, uploaded the new version to firefox website and added the new release here in github, thanks again for suggesting 👍

**Comment by haarp** [comment]
Awesome, that was fast, thanks! 🥇

**Comment by haarp** [comment]
Opening works, but could you also automatically focus the input field when it's being opened? Otherwise one still has to use the mouse, negating the point of the shortcut.

**Comment by Mohd-PH** [comment]
Ok, I tried simple HTML and JavaScript approach and didn't work, I will reopen the issue and will look into a solution in the future, you can double `tab` to focus in the input for now 😁

**Comment by Mohd-PH** [comment]
@haarp retried the same simple solution and it worked 😮. uploaded the new version to the store and here in github

**Comment by haarp** [comment]
Excellent, thanks!

**Comment by Mohd-PH** [comment]
You are welcome

**Comment by NoXPhasma** [comment]
@Mohd-PH I don't want to open a new issue, since it fits to this. `CTRL` + `SHIFT` + `F` is already used by a different extension in my installation. Would it be possible to add an option to change it?
