### ISSUE TITLE
Pressing Enter in regex field to trigger a search

### ISSUE THREAD

**Issue by peter-kehl** [Mohd-PH/RegexSearch#5]
Hi Mohd,

Thank you for RegexSearch.

When the focus is in the regex field, could you make it search on typing Enter, please. It saves mouse movement or several TABs.

**Comment by Mohd-PH** [comment]
Sure !

**Comment by Mohd-PH** [comment]
Done in [Search on clicking Enter key](https://github.com/Mohd-PH/RegexSearch/commit/de9d2b163ab6c78db04d236db3a73b7d25bd1e0b)

**Comment by Mohd-PH** [comment]
Uploaded the new version to firefox website and here in github, Thanks for suggesting 😃
