### ISSUE TITLE
Monospace fonts in regexInput

### ISSUE THREAD

**Issue by billpcs** [Mohd-PH/RegexSearch#7]
Is it possible that the input field for the _regex_ uses **Monospaced** fonts?

I find it a bit difficult to see what I am writing.

Thanks for this great tool!

**Comment by Mohd-PH** [comment]
Do you have a suggestion for a specific font?

**Comment by billpcs** [comment]
[Consolas](https://en.wikipedia.org/wiki/Consolas) is my favorite.

I have no problem, whatever else you choose though.

**Comment by Mohd-PH** [comment]
Cool, i will add this font

**Comment by Mohd-PH** [comment]
I couldn't find it in google fonts, what do you think about [Roboto Mono](https://fonts.google.com/specimen/Roboto+Mono)?

**Comment by billpcs** [comment]
Roboto Mono is cool! 

Maybe Consolas is LibreOffice/MS Word only. The link in wikipedia goes [here](https://fonts.google.com/specimen/Inconsolata) in Google Fonts. It is called Inconsolata.

**Comment by Mohd-PH** [comment]
Thanks for the suggestion, Used Robot mono and uploaded the new release to firefox website, and created a new release [here](https://github.com/Mohd-PH/RegexSearch/releases/tag/1.0.10) 😸
