### ISSUE TITLE
Keyboard shortcut to open the extension?

### ISSUE THREAD

**Issue by jaaquino** [Mohd-PH/RegexSearch#8]
First of all, this seems like a terrific extension -- regex searching ought to be standard in every browser. Alas... 

One little addition to this extension would help enormously: a keyboard shortcut to open the search box. Having to search for the icon on the toolbar slows things down immensely (and mousing about for it is poor ergonomics).

Can a keyboard shortcut to open the extension be added without much fuss?

Again, thank you for your work on this extension.

-j

**Comment by Mohd-PH** [comment]
Yeah it is already available, click CTRL+SHIFT+F to open the extension, I really need to write simple documentation 😸

**Comment by nathanhinchey** [comment]
On my mac <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>F</kbd> doesn't open the shortcut for me. 

Using Firefox Browser 73.0.1 (64-bit) on macOS Catalina Version 10.15.2

**Comment by mambusskruj** [comment]
Yep, `CTRL`+`SHIFT`+`F` doesn't work on macOS Ventura.
