### ISSUE TITLE
Result text is editable

### ISSUE THREAD

**Issue by theDragonFire** [Mohd-PH/RegexSearch#9]
I noticed that the `textarea` element that holds the results of the search is editable. It would make sense for it to be read-only, so, unless you intentionally left the `textarea` as editable, I would recommend adding the `readonly` attribute to the `textarea` element such that
`<textarea ... id="resultTextarea"></textarea>`
becomes
`<textarea ... id="resultTextarea" readonly></textarea>`

**Comment by Mohd-PH** [comment]
Thank you for your suggestion and pull request 😄

**Comment by Mohd-PH** [comment]
Uploaded the new version to mozilla addons website and here created a new release
